name: Yamel CD

on:
  push:
    branches: [ releases/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.x'
        otp-version: '22.3'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          _build/prod/lib
          deps
          doc
        key: ${{ runner.os }}-mix-prod-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-prod-

    - name: Install Dependencies
      run: mix deps.get

    - name: Build Dependencies
      env:
        MIX_ENV: prod
      run: mix deps.compile

    - name: Build Yamel
      env:
        MIX_ENV: prod
      run: mix compile

    - name: Build Docs
      env:
        MIX_ENV: prod
      run: mix docs

  check_package:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.x' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          _build/prod/lib
          deps
          doc
        key: ${{ runner.os }}-mix-prod-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-prod-

    - env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: mix hex.publish --dry-run

  publish_package:
    runs-on: ubuntu-latest
    needs: check_package

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          _build/prod/lib
          deps
          doc
        key: ${{ runner.os }}-mix-prod-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-prod-

    - env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: mix hex.publish --yes
