name: Yamel CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.x'
        otp-version: '22.3'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/test/lib
        key: ${{ runner.os }}-mix-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-test-

    - name: Install Dependencies
      run: mix deps.get

    - name: Build Dependencies
      env:
        MIX_ENV: test
      run: mix deps.compile

    - name: Build Yamel
      env:
        MIX_ENV: test
      run: mix compile

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.x'
        otp-version: '22.3'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/test/lib
        key: ${{ runner.os }}-mix-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-test-

    - env:
        MIX_ENV: test
      run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.8.x'
        otp-version: '22.3'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build/test/lib
        key: ${{ runner.os }}-mix-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-test-

    - run: mix test

  coverage:
    runs-on: ubuntu-latest
    needs: test

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.9.x'
          otp-version: '22.3'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build/test/lib
          key: ${{ runner.os }}-mix-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-test-

      - name: Build ExCoveralls
        run: mix compile excoveralls

      - name: Coverage Summary
        run: mix coveralls

      - name: Publish Coverage
        run: mix coveralls.github


  trigger-cd:
    runs-on: ubuntu-latest
    needs: coverage

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Trigger CD
        run: |
          if git rev-parse --verify; then
            echo "Version already exists."
          else
            git config user.name Lucasbot
            git config user.email lucas.primola@gmail.com
            git checkout -b releases/$(cat version)
            git push origin releases/$(cat version)
          fi
